export { default as dashboards } from './dashboard.svg'
export {default as accounts} from './accounts.svg'
 export {default as settings} from './settings solid 1.png'
 export {default as chip} from './Chip_Card.svg'
 export { default as creditCard} from './credit-card.png'
 export { default as investment} from './investment.svg'
 export {default as transactions} from './transactions.png'
 export { default as services} from './service 1.png'
 export {default as privileges} from './econometrics 1.png'
export { default as loans} from './loan 1.png'
export {default as pie} from './pie.png'
export { default as paypal } from './paypal.png'
export {default as jemi} from './jemi.png'
export {default as card} from './deposit.png'